name: Ubuntu
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
